#include "bimode.hpp"
#include "bimodeL.hpp"
#include "gag.hpp"
#include "gagL.hpp"
#include "gap.hpp"
#include "gapL.hpp"
#include "gshare.hpp"
#include "lxor.hpp"
#include "pag.hpp"
#include "pagL.hpp"
#include "pap.hpp"
#include "papL.hpp"

