#include "bimode.hpp"
#include "bimodeL.hpp"
#include "bimode_singleram.hpp"
#include "gag.hpp"
// #include "local_global_tage.hpp"
#include "gagL.hpp"
#include "gap.hpp"
#include "gapL.hpp"
#include "gshare.hpp"
#include "gshareL.hpp"
#include "lxor.hpp"
#include "lxorL.hpp"
#include "pag.hpp"
#include "pagL.hpp"
#include "pap.hpp"
#include "papL.hpp"
#include "tage_simple.hpp"
